Mudrod 168: Full Ingest 03/2017 logs fails
mudrod/mudrod pull request #171
Opened 2017-05-15 17:07 UTC by quintinali

2017-05-15 17:19 UTC, fgreg requested changes
Can you explain what you did exactly? It seems like this is just guarding against the case when clickstream/userhistory is empty, which is good, but isn't the root of the problem the fact that clickstream/userhistory is empty? Does this address that problem?

2017-05-15 17:19 UTC, fgreg commented on core/src/main/java/gov/nasa/jpl/mudrod/utils/MatrixUtil.java
> +          System.out.println("***************output null***************");
Delete this or make it a useful logging statement.

2017-05-15 17:20 UTC, fgreg commented on core/src/main/java/gov/nasa/jpl/mudrod/utils/MatrixUtil.java
> +          System.out.println("***************output null***************");
I'm talking about just the` System.out.println("***************output null***************");` statement.

2017-05-15 17:40 UTC, quintinali commented
@fgreg It is reasonable sometimes user history and clickstream matrix is empty

(1) user history matrix is what users searched in selected time. Each row is a user and each column is a query. A query should be searched multiple times which is larger than a predefined threshold or it will be discarded. 
(2) Clickstream data record which dataset users click or download after search a query. If users didn't click or download dataset after search a query, the matrix will be empty.
(3) In order to get more accurate sessions,  a session is discarded if it doesn't contain view or download behaviours. For February and March 2017, I can't find FTP logs ( record download behaviors). I think this is the main reason. 

So I decided to solve bugs related to the case when clickstream/userhistory is empty at first.

2017-05-15 17:56 UTC, fgreg commented
@quintinali ok, thanks for explaining. I'll test more recent logs and make sure it works. Do please remove that println statement though.

2017-05-16 21:36 UTC, lewismc commented on core/src/main/java/gov/nasa/jpl/mudrod/weblog/process/ClickStreamAnalyzer.java
> +        svd.saveToES(tripleList, props.getProperty("indexName"), props.getProperty("clickStreamLinkageType"));
@quintinali please use MudrodConstants for all of these property lookup's. Thank you

2017-05-16 21:36 UTC, lewismc requested changes
Please consider comments @quintinali thank you

2017-05-17 03:58 UTC, lewismc commented
Hi @quintinali this seems to have fixed the bug. The only issue I get now is as follows
```
2017-05-16 20:56:38,203 INFO  process.MetadataAnalyzer (MetadataAnalyzer.java:execute(66)) - *****************Metadata Analyzer starts******************
org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/usr/local/mudrod_resources/weekly_logs/2016/11/w1/MetadataMatrix.csv
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:251)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:270)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:202)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.ZippedWithIndexRDD.<init>(ZippedWithIndexRDD.scala:44)
	at org.apache.spark.rdd.RDD$$anonfun$zipWithIndex$1.apply(RDD.scala:1293)
	at org.apache.spark.rdd.RDD$$anonfun$zipWithIndex$1.apply(RDD.scala:1293)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.zipWithIndex(RDD.scala:1292)
	at org.apache.spark.api.java.JavaRDDLike$class.zipWithIndex(JavaRDDLike.scala:342)
	at org.apache.spark.api.java.AbstractJavaRDDLike.zipWithIndex(JavaRDDLike.scala:45)
	at gov.nasa.jpl.mudrod.utils.MatrixUtil.loadVectorFromCSV(MatrixUtil.java:359)
	at gov.nasa.jpl.mudrod.semantics.SVDAnalyzer.getSVDMatrix(SVDAnalyzer.java:59)
	at gov.nasa.jpl.mudrod.metadata.process.MetadataAnalyzer.execute(MetadataAnalyzer.java:74)
	at gov.nasa.jpl.mudrod.discoveryengine.MetadataDiscoveryEngine.process(MetadataDiscoveryEngine.java:67)
	at gov.nasa.jpl.mudrod.main.MudrodEngine.startFullIngest(MudrodEngine.java:261)
	at gov.nasa.jpl.mudrod.main.MudrodEngine.main(MudrodEngine.java:401)
2017-05-16 20:56:38,224 INFO  process.MetadataAnalyzer (MetadataAnalyzer.java:execute(85)) - *****************Metadata Analyzer ends******************Took 0s
```

2017-05-17 03:59 UTC, lewismc commented
I am +1 to merge this pull request into master branch and we can work towards improving logging and the error handling in subsequent pull requests.

2017-05-17 04:00 UTC, merged

2017-05-17 04:04 UTC, quintinali commented
@Yongyao Could you please take a look at the issue Lewis mentioned above. I think it is related to metadata harvest and analysis.

2017-05-17 04:09 UTC, Yongyao commented
@lewismc Can you elaborate on what data and command you were using?

2017-05-17 05:54 UTC, lewismc commented
Yes sorry
Data is from [here](ftp://podaac.jpl.nasa.gov/misc/outgoing/cjf/mudrod/2017/04/)
Command is as follows
```
./core/target/appassembler/bin/mudrod-engine -f -dataDir /usr/local/mudrod_resources/weekly_logs/2017/04/w1/
```
I took WWW, WWWssl and FTP logs for week 1 and put them into ```/usr/local/mudrod_resources/weekly_logs/2017/04/w1/```